### ISSUE TITLE
Editing a borrower

### ISSUE THREAD

**Issue by s-kennedy** [velo-vanier/vv-ui#5]
- all fields are editable

**Comment by fraserreed** [comment]
Editing a user can be done using:

PUT http://eb66bc8f.ngrok.io/api/users/<ID_User>

Request header: "Content-Type: application/json"

Payload is JSON, like this:

```
{
  "FirstName": "Borrower3 FirstName",
  "LastName": "Borrower3 LastName",
  "Email": "borrower3@otherdomain.com",
  "Phone": "613-675-4444",
  "Password": "3453534v34vv"
}
```

The response will be a fully populated user record.

If the request validation fails, a 422 response should be returned with a message similar to this for the fields that failed:

```
{
  "LastName": [
    "The last name field is required."
  ]
}
```

**Comment by magicops** [comment]
Done and the UI is on #1
